spring.application.name=server
#server.servlet.context-path=/mcp
spring.datasource.url=jdbc:mysql://localhost:3306/cloud?serverTimeZone=UTC
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.config.import=optional:file:.env[.properties]

spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true
